# Generated by Django 3.1.4 on 2020-12-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponcode',
            options={'ordering': ('created',), 'verbose_name': 'CouponCode'},
        ),
    ]
